select * from article;

create table ARTICLE
(
    id      bigint generated by default as identity,
    name    varchar(255),
    title   varchar(255),
    context varchar(255),
    primary key (id)
);
